USE ProjectTracker

INSERT INTO PROYECTO
VALUES
    ('Desarrollo de un sistema de gestión de inventario', 'Creación de una aplicación web para el seguimiento y gestión de inventarios empresariales.', '2023-05-15', 3),
    ('App de fitness personalizada', 'Desarrollo de una aplicación móvil para la planificación y seguimiento de rutinas de ejercicio personalizadas.', '2023-07-03', 3),
    ('Plataforma de aprendizaje en línea', 'Creación de un sitio web para cursos en línea con funcionalidades avanzadas de interacción y evaluación.', '2023-09-21', 3),
    ('Sistema de reservas para hoteles', 'Desarrollo de un sistema de reservas en línea para hoteles con integración de pagos y gestión de disponibilidad.', '2023-11-12', 3),
    ('App de gestión financiera personal', 'Creación de una aplicación móvil para el seguimiento de gastos, ingresos y presupuestos personales.', '2024-01-02', 3),
    ('Plataforma de blogging', 'Desarrollo de un sitio web para la publicación y gestión de blogs con características avanzadas de personalización.', '2024-02-18', 3),
    ('Juego móvil de puzzle', 'Creación de un juego móvil de puzzle con mecánicas originales y gráficos atractivos.', '2024-04-05', 3),
    ('Sistema de gestión de proyectos', 'Desarrollo de una aplicación web para la planificación y seguimiento de proyectos empresariales.', '2024-06-22', 3),
    ('App de recomendaciones de películas', 'Creación de una aplicación móvil para recomendar películas según los gustos del usuario.', '2024-08-11', 3),
    ('Plataforma de crowdfunding', 'Desarrollo de un sitio web para la financiación colectiva de proyectos creativos y empresariales.', '2024-09-29', 3),
    ('Sistema de gestión de citas médicas', 'Creación de un sistema en línea para la gestión de citas médicas y seguimiento de historiales de pacientes.', '2024-11-17', 3),
    ('Juego de rol multijugador en línea (MMORPG)', 'Desarrollo de un juego en línea de mundo abierto con características de juego de rol.', '2025-01-05', 3),
    ('App de seguimiento de hábitos', 'Creación de una aplicación móvil para el seguimiento y establecimiento de hábitos saludables.', '2025-02-23', 3),
    ('Plataforma de streaming de música', 'Desarrollo de un sitio web para la reproducción en línea de música con funciones sociales integradas.', '2025-04-12', 3),
    ('Sistema de gestión de recursos humanos (RRHH)', 'Creación de una aplicación web para la gestión integral de recursos humanos en empresas.', '2025-05-30', 3),
    ('App de aprendizaje de idiomas', 'Desarrollo de una aplicación móvil para el aprendizaje interactivo de idiomas extranjeros.', '2025-07-17', 3),
    ('Plataforma de reserva de actividades turísticas', 'Creación de un sitio web para la reserva en línea de actividades turísticas y experiencias locales.', '2025-09-04', 3),
    ('Sistema de gestión de contenido (CMS)', 'Desarrollo de una aplicación web para la creación y gestión de contenido digital.', '2025-10-22', 3),
    ('App de gestión de tareas', 'Creación de una aplicación móvil para la organización y seguimiento de tareas personales y profesionales.', '2025-12-09', 3),
    ('Juego de estrategia en tiempo real (RTS)', 'Desarrollo de un juego de estrategia en tiempo real con elementos de gestión de recursos.', '2026-01-27', 3),
    ('Plataforma de venta de productos artesanales', 'Creación de un sitio web para la venta en línea de productos artesanales y de autor.', '2026-03-15', 3),
    ('Sistema de gestión de almacenes', 'Desarrollo de una aplicación web para la gestión eficiente de almacenes y logística.', '2026-05-02', 3),
    ('App de meditación y mindfulness', 'Creación de una aplicación móvil para la práctica guiada de meditación y técnicas de mindfulness.', '2026-06-20', 3),
    ('Plataforma de análisis de datos', 'Desarrollo de un sitio web para el análisis y visualización de datos empresariales.', '2026-08-07', 3),
    ('Sistema de gestión de flotas de vehículos', 'Creación de una aplicación web para la gestión de flotas de vehículos comerciales.', '2026-09-25', 3),
    ('App de planificación de viajes', 'Desarrollo de una aplicación móvil para la planificación y reserva de viajes personalizados.', '2026-11-13', 3),
    ('Plataforma de intercambio de libros', 'Creación de un sitio web para el intercambio y préstamo de libros entre usuarios.', '2026-12-31', 3),
    ('Sistema de gestión de eventos', 'Desarrollo de una aplicación web para la organización y gestión de eventos corporativos y sociales.', '2027-02-18', 3),
    ('App de asesoramiento nutricional', 'Creación de una aplicación móvil para el asesoramiento personalizado en nutrición y dietética.', '2027-04-07', 3),
    ('Plataforma de venta de cursos en línea', 'Desarrollo de un sitio web para la venta y distribución de cursos en línea sobre diversos temas.', '2027-05-25', 3);
